(function (window, document) {
  'use strict';
  var resources = window.MoonshineData && Array.isArray(window.MoonshineData.resources) ? window.MoonshineData.resources : [];
  var tools = [
    { id: 'funding-readiness', name: 'Funding Readiness Checklist', job: 'qualify', type: 'Qualification', description: 'Organize the basic signals and documents before a funding conversation.', href: './tools/funding-readiness-checklist.html', when: 'Use before Product Desk or a client handoff.' },
    { id: 'sales-script', name: 'Sales Script Generator', job: 'sell', type: 'Explain', description: 'Draft permission-based email, SMS, DM, call, and warm-intro language.', href: './tools/sales-script-generator.html', when: 'Use when the client or referral partner needs a clear next message.' }
  ];
  var calculators = [{ id: 'commission-simulator', name: 'Commission Simulator', job: 'calculate', type: 'Planning', description: 'Model example partner scenarios from volume, rates, and funding assumptions.', href: './tools/commission-simulator.html', when: 'Use for internal planning only; not a payout forecast.' }];
  var ai = [{ id: 'partner-signup-copilot', name: 'Partner Signup Copilot', job: 'automate', type: 'Published GPT', description: 'Guide prospective partners through safe intake and onboarding questions.', href: 'https://chatgpt.com/g/g-6a590d96d96081919ef39a52a68d222a-partner-signup-copilot', when: 'Use for partner onboarding, never borrower funding applications.' }];
  var list = document.querySelector('[data-build-list]');
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function row(item) { return '<article class="build-row" data-build-item data-job="' + escapeHtml(item.job) + '" data-search="' + escapeHtml((item.name + ' ' + item.description + ' ' + item.type).toLowerCase()) + '"><div><span class="mpc-badge mpc-badge-info">' + escapeHtml(item.type) + '</span><h3>' + escapeHtml(item.name) + '</h3></div><div><p>' + escapeHtml(item.description) + '</p><small>' + escapeHtml(item.when) + '</small></div><div class="build-row-actions"><a class="mpc-button mpc-button-outline mpc-button-sm" href="' + escapeHtml(item.href) + '"' + (item.href.indexOf('https://') === 0 ? ' target="_blank" rel="noopener"' : '') + '>Open Tool</a></div></article>'; }
  function render(target, items, empty) { var node = document.querySelector(target); if (node) node.innerHTML = items.length ? items.map(row).join('') : '<div class="mpc-empty"><strong>' + escapeHtml(empty) + '</strong><p>No connected inventory is available for this job.</p></div>'; }
  function renderAll() { var filter = document.querySelector('[data-build-filter]').value; var search = document.querySelector('[data-build-search]').value.toLowerCase(); var items = tools.concat(ai, calculators).concat(resources.map(function (item) { return { id: item.id, name: item.title, job: 'research', type: item.type || 'Resource', description: item.summary || item.description || 'Partner resource.', href: item.href || '', when: 'Use when this operating task matches the resource.' }; })); var filtered = items.filter(function (item) { return (filter === 'all' || item.job === filter) && (!search || (item.name + ' ' + item.description + ' ' + item.type).toLowerCase().indexOf(search) >= 0); }); if (list) list.innerHTML = filtered.length ? filtered.map(row).join('') : '<div class="mpc-empty"><strong>No matching build item.</strong><p>Broaden the job or search terms. No invented tools are shown.</p></div>'; }
  render('[data-build-tools]', tools, 'No local operator tools connected.');
  render('[data-build-ai]', ai, 'No published AI assistants connected.');
  render('[data-build-resources]', resources.map(function (item) { return { name: item.title, job: 'research', type: item.type || 'Resource', description: item.summary || item.description, href: item.href || '', when: 'Use when this operating task matches the resource.' }; }), 'No resources connected.');
  render('[data-build-calculators]', calculators, 'No calculators connected.');
  if (list) { document.querySelector('[data-build-filter]').addEventListener('change', renderAll); document.querySelector('[data-build-search]').addEventListener('input', renderAll); renderAll(); }
})(window, document);