(function (window, document) {
  'use strict';
  var leads = window.MoonshineData && Array.isArray(window.MoonshineData.sampleLeads) ? window.MoonshineData.sampleLeads : [];
  var commissions = window.MoonshineData && window.MoonshineData.sampleCommissions ? window.MoonshineData.sampleCommissions : null;
  var form = document.querySelector('[data-earn-plan]');
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function money(value) { return '$' + Math.round(Number(value) || 0).toLocaleString(); }
  function number(name, fallback) { var field = form && form.elements[name]; var value = Number(field && field.value); return Number.isFinite(value) ? value : fallback; }
  function renderPlan() { var income = number('income_goal', 0); var commission = number('avg_commission', 0); var fundedRate = number('funded_rate', 0) / 100; var submittedRate = number('submitted_rate', 0) / 100; var qualifiedRate = number('qualified_rate', 0) / 100; var funded = commission > 0 ? Math.ceil(income / commission) : 0; var submitted = fundedRate > 0 ? Math.ceil(funded / fundedRate) : 0; var qualified = submittedRate > 0 ? Math.ceil(submitted / submittedRate) : 0; var conversations = qualifiedRate > 0 ? Math.ceil(qualified / qualifiedRate) : 0; var target = document.querySelector('[data-earn-plan-results]'); if (target) target.innerHTML = [['Funded clients needed', funded, 'Planning output'], ['Submitted needed', submitted, 'Uses editable funded rate'], ['Qualified opportunities', qualified, 'Uses editable submitted rate'], ['Conversations needed', conversations, 'Uses editable qualified rate']].map(function (item) { return '<div class="earn-metric"><strong>' + escapeHtml(item[1]) + '</strong><span>' + escapeHtml(item[0]) + ' / ' + escapeHtml(item[2]) + '</span></div>'; }).join(''); }
  function renderProduction() { var statuses = [{ id: 'new', label: 'Leads' }, { id: 'reviewing', label: 'Reviewing' }, { id: 'submitted', label: 'Submitted' }, { id: 'funded', label: 'Funded' }]; var active = leads.filter(function (lead) { return ['new', 'reviewing', 'needsInfo', 'submitted', 'funded'].indexOf(lead.status) >= 0; }); var funded = leads.filter(function (lead) { return lead.status === 'funded'; }); var submitted = leads.filter(function (lead) { return lead.status === 'submitted'; }); var activeVolume = active.reduce(function (sum, lead) { return sum + Number(lead.fundingNeed || 0); }, 0); var fundedVolume = funded.reduce(function (sum, lead) { return sum + Number(lead.fundingNeed || 0); }, 0); var target = document.querySelector('[data-earn-production]'); if (target) target.innerHTML = [['Active pipeline', active.length, 'Demo leads in motion'], ['Submitted volume', money(submitted.reduce(function (sum, lead) { return sum + Number(lead.fundingNeed || 0); }, 0)), 'Requested volume / demo'], ['Funded clients', funded.length, 'Demo status only'], ['Funded volume', money(fundedVolume), 'Requested volume / demo']].map(function (item) { return '<div class="earn-metric"><strong>' + escapeHtml(item[1]) + '</strong><span>' + escapeHtml(item[0]) + ' / ' + escapeHtml(item[2]) + '</span></div>'; }).join(''); var stages = document.querySelector('[data-earn-stages]'); if (stages) stages.innerHTML = statuses.map(function (stage) { var items = leads.filter(function (lead) { return lead.status === stage.id; }); return '<div class="earn-stage-row"><strong>' + escapeHtml(stage.label) + '</strong><span><strong>' + escapeHtml(items.length) + '</strong><small>Canonical status: ' + escapeHtml(stage.id) + '</small></span><span>' + escapeHtml(money(items.reduce(function (sum, lead) { return sum + Number(lead.fundingNeed || 0); }, 0))) + '</span><a class="mpc-button mpc-button-ghost mpc-button-sm" href="./dashboard.html#leads">Open Pipeline</a></div>'; }).join('') + '<div class="mpc-disclaimer">Active requested volume across demo records: ' + escapeHtml(money(activeVolume)) + '. Approved volume is not available in the current lead contract.</div>'; }
  function renderCommissions() { var target = document.querySelector('[data-earn-commissions]'); if (!target) return; if (!commissions || !Array.isArray(commissions.rows) || !commissions.rows.length) { target.innerHTML = '<div class="mpc-empty earn-empty"><strong>No commission records connected.</strong><p>Verified compensation records will appear here when a live commission payload is available.</p><a class="mpc-button mpc-button-outline" href="./build.html#calculators">Open Planning Calculator</a></div>'; return; } target.innerHTML = '<div class="mpc-disclaimer">' + escapeHtml(commissions.disclaimer || 'Demo commission records only.') + '</div>' + commissions.rows.map(function (row) { return '<div class="earn-ledger-row"><div><strong>' + escapeHtml(row.businessName) + '</strong><small>' + escapeHtml(row.leadId) + '</small></div><div><strong>' + escapeHtml(row.productType || 'Product not recorded') + '</strong><small>' + escapeHtml(row.notes || '') + '</small></div><span>' + escapeHtml(row.fundedAmount == null ? 'Not funded' : money(row.fundedAmount)) + '</span><span><span class="mpc-badge mpc-badge-warning">' + escapeHtml(row.status) + '</span><small>' + escapeHtml(row.commissionAmount ? money(row.commissionAmount) : 'No amount') + ' / demo</small></span></div>'; }).join(''); }
  if (form) { form.addEventListener('submit', function (event) { event.preventDefault(); renderPlan(); }); form.addEventListener('input', renderPlan); }
  renderPlan(); renderProduction(); renderCommissions();
})(window, document);