(function (window, document) {
  'use strict';
  var namespace = 'moonshine.partnerOS.';
  var progressKey = namespace + 'trainingProgress';
  var modules = window.MoonshineData && Array.isArray(window.MoonshineData.trainingModules) ? window.MoonshineData.trainingModules.slice().sort(function (a, b) { return (a.order || 0) - (b.order || 0); }) : [];
  var resources = window.MoonshineData && Array.isArray(window.MoonshineData.resources) ? window.MoonshineData.resources : [];
  var scripts = resources.filter(function (item) { return (item.tags || []).some(function (tag) { return /script|intro|follow-up/i.test(tag); }) || /script|intro|follow-up/i.test(item.title); });
  var sprint = [
    { phase: 'Days 1–3', objective: 'SETUP', action: 'Complete your profile, confirm the Funding Page, and learn the Partner Command path.', training: 'Partner Orientation', href: './growth.html', label: 'Open Growth' },
    { phase: 'Week 1', objective: 'FOUNDATION', action: 'Complete the core orientation and compliance modules, then identify the first conversation to have.', training: 'Compliance Basics', href: '#training', label: 'Open Training' },
    { phase: 'Week 2', objective: 'CONVERSATIONS', action: 'Use a permission-based script, speak with a business owner or referral partner, and log the next lead action.', training: 'COI Referral Conversations', href: '#scripts', label: 'Open Scripts' },
    { phase: 'Week 3', objective: 'PIPELINE', action: 'Review follow-up, qualify the need, and use Product Desk when a product path needs comparison.', training: 'Lead Intake Workflow', href: './capital.html#product-desk', label: 'Open Product Desk' },
    { phase: 'Week 4', objective: 'CONSISTENCY', action: 'Review activity, identify the bottleneck, and choose the next training or resource action.', training: 'Dashboard Ops and Local Data', href: './dashboard.html#overview', label: 'Open Command' }
  ];
  function readProgress() { try { var value = JSON.parse(window.localStorage.getItem(progressKey) || '{}'); return value && typeof value === 'object' ? value : {}; } catch (error) { return {}; } }
  function writeProgress(value) { try { window.localStorage.setItem(progressKey, JSON.stringify(value)); } catch (error) {} }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function resource(id) { return resources.find(function (item) { return item.id === id; }); }
  function renderTraining() { var target = document.querySelector('[data-learn-training]'); var progress = readProgress(); var complete = modules.filter(function (item) { return progress[item.id]; }).length; document.querySelector('[data-learn-progress]').style.setProperty('--learn-progress', (modules.length ? Math.round(complete / modules.length * 100) : 0) + '%'); if (target) target.innerHTML = modules.length ? modules.map(function (item) { var done = Boolean(progress[item.id]); var related = resource((item.resourceIds || [])[0]); return '<article class="learn-row"><div><span class="mpc-badge ' + (done ? 'mpc-badge-success' : 'mpc-badge-warning') + '">' + (done ? 'Complete' : 'Not started') + '</span></div><div><h3>' + escapeHtml(item.title) + '</h3><p>' + escapeHtml(item.summary) + '</p><small>' + escapeHtml(item.track) + ' / ' + escapeHtml(item.durationMinutes) + ' MIN' + (related ? ' / Resource: ' + escapeHtml(related.title) : '') + '</small></div><div class="learn-row-actions"><button class="mpc-button mpc-button-outline mpc-button-sm" type="button" data-toggle-training="' + escapeHtml(item.id) + '">' + (done ? 'Mark Incomplete' : 'Mark Complete') + '</button>' + (related ? '<a class="mpc-button mpc-button-ghost mpc-button-sm" href="' + escapeHtml(related.href || './resources.html') + '">Open Resource</a>' : '') + '</div></article>'; }).join('') : '<div class="mpc-empty"><strong>No training modules connected.</strong><p>The learning inventory is not available yet.</p></div>'; }
  function renderSprint() { var target = document.querySelector('[data-learn-sprint]'); if (target) target.innerHTML = sprint.map(function (item) { return '<article class="learn-mission"><strong>' + escapeHtml(item.phase) + '<br>' + escapeHtml(item.objective) + '</strong><div><h3>' + escapeHtml(item.action) + '</h3><p>Related training: ' + escapeHtml(item.training) + '</p></div><a class="mpc-button mpc-button-outline mpc-button-sm" href="' + escapeHtml(item.href) + '">' + escapeHtml(item.label) + '</a></article>'; }).join(''); }
  function renderScripts() { var target = document.querySelector('[data-learn-scripts]'); if (target) target.innerHTML = scripts.length ? scripts.map(function (item) { return '<article class="learn-row"><div><span class="mpc-badge mpc-badge-info">' + escapeHtml(item.type || 'Resource') + '</span></div><div><h3>' + escapeHtml(item.title) + '</h3><p>' + escapeHtml(item.summary || item.description) + '</p><small>Use for: ' + escapeHtml((item.tags || []).join(', ')) + '</small></div><div class="learn-row-actions"><a class="mpc-button mpc-button-primary mpc-button-sm" href="' + escapeHtml(item.href || './resources.html') + '">Open Script Resource</a><a class="mpc-button mpc-button-ghost mpc-button-sm" href="./dashboard.html#leads">Open Pipeline</a></div></article>'; }).join('') : '<div class="mpc-empty"><strong>No script resources connected.</strong><p>Use the full Resource Library when conversation copy is assigned.</p></div>'; }
  document.addEventListener('click', function (event) { var button = event.target.closest('[data-toggle-training]'); if (!button) return; var progress = readProgress(); var id = button.getAttribute('data-toggle-training'); progress[id] = !progress[id]; writeProgress(progress); renderTraining(); });
  renderTraining(); renderSprint(); renderScripts();
})(window, document);